version: 2.1

orbs:
  msix: circleci/microsoft-msix@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  win: circleci/windows@2.4.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test_using-sln:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - msix/pack:
          working-dir: sample/Sample
          import-cert: true
          signing-cert: MSIX_SIGNING_CERT # I messed up when setting this.
  integration-test_using-exe:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - msix/pack:
          working-dir: sample/SampleExe
          using-sln: false
          mapping-file: mapping.txt
          manifest-file: appxmanifest.xml
      - msix/sign:
          working-dir: sample/SampleExe
          package-name: circleci-cli
          signing-cert: MSIX_SIGNING_CERT
          certificate-fingerprint: "91E805BC501F4951E2B48E222DA6C3D882BFA683"

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - orb-tools/publish-dev:
          orb-name: circleci/microsoft-msix
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test_using-sln
      - integration-test_using-exe
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/microsoft-msix
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test_using-sln
            - integration-test_using-exe
          filters:
            branches:
              only:
                - master
                - main
